name: Manual Update on Commit
on: 
  push:
jobs:
  Update_README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Run .NET Project
        working-directory: ./dotnet
        run: dotnet run
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"

          git commit -am "Update README by Manual Commit" -m "Sent a request to the WakaTime JSON API. This action has been triggered by a ${{ github.event_name }} event"
          git push
