name: README Update Schedule Action
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - run: dotnet run --project ./dotnet
      - name: Commit and push changes
        run: |
          git config --global user.name "kasp470f"
          git config --global user.email "11627@student.eadania.dk"

          git add -A
          git commit -m "Daily Update to README.md"
          git push
