name: Schedule Update Action to .README Programming Languages Section
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * 5'
jobs:
  Update_README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Run .NET Project
        working-directory: ./dotnet
        run: dotnet run
      - name: Commit and push changes
        run: |
          git config --global user.name "ReadME [BOT]"
          git config --global user.email "username@users.noreply.github.com"

          git commit -am "Weekly Update to README" -m "Sent a request to the WakaTime JSON API. This action has been triggered by a ${{ github.event_name }} event"
          git push
